Page/admin hall reservations
phys3/speck-academy-booking-app-client pull request #4
Opened 2019-05-31 16:13 UTC by Goran202

2019-06-10 13:38 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +  box-sizing: border-box;
box-sizing je postavljen globalno tako da ovo nije potrebno

2019-06-10 13:39 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +  font-style: normal;
većina ovih "normal" vrijednosti je defaultna tako da su ovi stilovi suvišni

2019-06-10 13:39 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +const Title = styled.div`
očekujem da je Title neki `<h>` element a ne običan `<div>`

2019-06-10 13:41 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +const Opis = styled.div`
komp moraju imati ENG imena

2019-06-10 13:42 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +const SlimText = styled.div`
ime komponente indicira da bi ovo trebao biti tipografski element tipa `<h>` ili `<p>`

2019-06-10 13:43 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +const MidPart = styled.div`
ovo ime ništa ne govori... u pravilu bi imena komponenti trebala biti deskriptivna i usko vezana uz funkciju komponente...

2019-06-10 13:44 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +const Rectangle = styled.div`
koristiti deskriptivnije ime

2019-06-10 13:44 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +const BigRectangle = styled.div`
koristiti deskriptivnije ime

2019-06-10 13:45 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +import React from 'react';
ovi stilovi se trebaju nalaziti u modulu AdminEditHallStyle.js

2019-06-10 13:46 UTC, ispoljari commented on src/UI/admin/components/edit-hall/AdminEditHall.js
> +const EditHallComponent = () => (
u biti bi jedino ova komponenta trebala bidi u ovom JS modulu

2019-06-10 13:48 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/style.js
> +import styled from 'styled-components';
ovaj modul bi se trebao zvati AdminHallReservationStyle

2019-06-10 13:49 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +let daysOfWeekNumerals = [1, 2, 3, 4, 5, 6, 0];
const DAYS_OF_WEEK_NUMERALS umj. ovoga što si napisao

2019-06-10 13:49 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +let daysOfWeek = ['PON', 'UTO', 'SRI', 'ČET', 'PET', 'SUB', 'NED'];
const DAYS_OF_WEEK umj. ovoga što si napisao

2019-06-10 13:50 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +let hoursOfDay = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]; //hour 22 is different
const ...

2019-06-10 13:50 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +function myFunction() {
koja je svrha ove funkcije?

2019-06-10 13:52 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +  console.log(startTime + ' ' + endTime);
makni sve console.log - ove iz ovog modula jer ne smiju završiti u production-u

2019-06-10 13:54 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +let isVisible = true;
koja je svrha ove globalne varijable?

2019-06-10 13:55 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +  const offset = 69;
ovo ne treba biti u posebnoj varijabli

2019-06-10 14:00 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +  let existStartLength = {
const EXIST_START_LENGTH

2019-06-10 14:08 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +  existStartLength.start = existStartLength.start / 1000 / 60 / 60;
bilo bi bolje da si na samom objektu existsStartLength deklarirao metode sa deskriptivnim imenima matematičkih operacija koje dolje izvršavaš... npr: 
``` 
const EXIST_START_LENGTH = {
  exist: true,
  start: 0,
  length: 0,
  shiftStartTime(timeShiftFaktor) {
    this.start = this.start - timeShiftFaktor;
  },
  transformStartTimeToPixels(pixelTransformFaktor) {
    this.start = this.start*pixelTransformFaktor
  },
  ...
};

existStartLength.shiftStartTime(8);
existStartLength.transformStartTimeToPixels(50);
...
```

Razbijanjem koda u manje funkcije, deskriptivnog imena, sa jednom odgovornošću, kod postaje čitljiviji. U tom slučaju ti ne trebaju komentari za objašnjavanje koda jer je isti "self explanatory"

2019-06-10 14:10 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +function refresfInfo() {}
makni ove funkcije koje nemaju svrhu

2019-06-10 14:14 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +  constructor(props) {
constructor i sav sadržaj unutar njega zamjeni sa novijom sintaksom deklariranja state-a; 
```
state = {
  dummyData: dataArray,
  test: 55,
  currentReservationActive: {
  ...
  }
}
```

2019-06-10 14:28 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +              {hoursOfDay.map(hour => {
Ovu logiku izvuci u metodu klase sa dobrim imenom, pa ju ovdje pozovi. Unutar te metode deklariraj hoursOfDay, a ne kao globalnu varijablu, s obzirom da ju ne koristiš nigdje  drugdje

2019-06-10 14:33 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +  render() {
Render metoda ti je jako "napuhana" i teško čitljiva. Potrebno ju je razbiti u manje djelove. U React-u se to generalno radi na dva načina. Možeš parent komponentu razbiti na još manje komponente. Međutim, mislim da bi to dodalno nepotrebno slojeve apstrakcije jer bi morali stvoriti nekoliko novih folder/modula/fajlova i decentralizirati "srodnu" logiku. Mislim da je bolje da u ovom slučaju to izvedemo sa sub-render metodama. Razbij cijelu logiku renderiranja u manje logičke cjeline prema SRP principu.

2019-06-10 14:45 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +            {daysOfWeekNumerals.map(day => {
Ovo je ogromna količina koda koju bi trebalo staviti u subRender metodu. Mislim da je u ovom slučaju bolje napraviti novu funkcionalnu komponentu u posebnom modulu, sa svojim styled-componentsima i importati ju ovaj fajl. Ako postoje parametri koji su varijabilni npr. property-ji iz state-a, možeš ih prosljediti kao prop u tu komponentu. izaberi neko dobro ime komponente.

2019-06-10 14:54 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +                  {this.state.dummyDataArray[0].hallReservaltions.map(
Ovo treba odvojiti u subrender metodu novostvorene subkomponente. Možeš ju nazvati renderDummyDataCollection.... Makni sve ove console.log-ove... Sve varijable definiraj na vrhu ove metode, npr.
```
const reservationTimeData = {
 reservationDate,
 reservationStartTime,
 reservationEndTime
}
```

2019-06-10 14:58 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +                            onClick={() => {
Ovdje ćeš umjesto direktnog postavljanja state-a aktivirati calllback funkciju prosljeđenu iz parent komponente (inverzna komunikacija, down-top princip demonstriran na predavanju). U callback metodi parent-a ćeš promjeniti state

2019-06-10 14:58 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +                            <PopUpInfo>
Sve ovo., unutar PopUpInfo, može biti u novoj komponenti ili novoj subrender metodi.

2019-06-10 15:00 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +    return (
prije return statement-a, na početku render metode, destrukturiraj sve potrebne parametre iz state-a npr const { dummyDataArray, currentReservationsActive } = this.state

2019-06-10 15:01 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +          <Info>
obriši sve ove iskomentirane linije koda

2019-06-10 15:03 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +              onClick={() => {
Svu ovu logika unutar onClick event listenera treba odvojiti u posebnu metodu (event handler) koju ćeš pozvati na slj. način `onClick = {this.handleDetailsClick}`

2019-06-10 15:09 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +                this.setState({
Set-aj state na način na koji sam napisao na slacku (odg. na tvoje pitanje) 
```
{...this.state, 
  currentReservationsActive : {
    ...this.state.currentReservationsActive,
    reservationTitle: bla blblbl,
}}
```

Iako mi nije jasno što ti ovdje točno radiš. Uzmeš value nekog property-ja iz state-a i onda ga assigneaš u isti taj property... npr 
`reservationTitle: this.state.currentReservationActive.reservationTitle,` ???

2019-06-10 15:11 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/AdminHallReservation.js
> +}
uff... skoro sam umro dešifrirajući ovaj špageti kod :D molim te razbij to u manje cjeline prema uputama... inače, što se tiče funkcionalnosti i logike, nice job

2019-06-10 15:12 UTC, ispoljari commented on src/UI/admin/components/hall-reservation/newData.js
> +const dataArray = [
ovo neću kontrolirati jer je to dummy objekt

2019-06-10 15:14 UTC, ispoljari requested changes
refaktor koda prema danim komentarima

2019-06-11 11:57 UTC, Goran202 commented
Hvala za review. Refaktorirat ću čim ulovim vremena (I komentirati neke tvoje komentare ako bude potrebno). 
P.S. Komentirao i fajlove koji nisu "moji", a onda moguće nisi te komentare upisao u PR gdje je trebalo ići. To je src/UI/admin/components/edit-hall/AdminEditHall.js (prvih 10 komentara)

2019-06-12 20:43 UTC, merged