Admin halls page
phys3/speck-academy-booking-app-client pull request #6
Opened 2019-06-02 15:12 UTC by igorsustic

2019-06-03 15:42 UTC, ispoljari commented on src/UI/admin/components/available-hall/AddHall.js
> +import React from 'react';
ovu komponentu stavi u novi folder add-hall i nazovi AdminAddHall

2019-06-03 15:43 UTC, ispoljari commented on src/UI/admin/components/available-hall/AddHall.js
> +  box-sizing: border-box;
ovo nije potrebno jer je već deklarirano globalno

2019-06-03 15:45 UTC, ispoljari commented on src/UI/admin/components/available-hall/AddHall.js
> +  height: 400px;
height property se ne postavlja eksplicitno, nego je sadržaj taj koji određuje konačnu visinu

2019-06-03 15:50 UTC, ispoljari commented on src/UI/admin/components/available-hall/AddHall.js
> +const ButtonAdd = styled.div`
Koristi button element a ne div da bi implementirao funkcionalnost buttona.

2019-06-03 15:51 UTC, ispoljari commented on src/UI/admin/components/available-hall/AddHall.js
> +  font-style: normal;
ovdje ima puno nepotrebnih linija koda jer ti property-ji defaultno imaju vrijednost "normal"

2019-06-03 15:52 UTC, ispoljari commented on src/UI/admin/components/available-hall/AddHall.js
> +const AddHallComponent = () => (
Kod unutar komponente AddHallComponent ide u poseban modul koji se mora zvati AdminAddHall.js (unutar trenutnog foldera) i komponenta koja se exporta iz tog modula mora imati isto ime kao i folder...

2019-06-03 15:54 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +  height: 400px;
height property se ne postavlja explicitno u ovom slučaju, nego je sadržaj taj koji određuje visinu komponente

2019-06-03 15:57 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +const Wrapper = styled.div`
Ova komponenta je identična Wrapper komponenti za AdminAddHall. Nemoj duplicirati kod

2019-06-03 16:03 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +  width: 374px;
ne treba definirati width na svakoj komponenti. Dovoljno je na wrapperu

2019-06-03 16:03 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +  height: 40px;
Height se ne definira. Sadržaj određuje height...

2019-06-03 16:04 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +const Title = styled.h1`
height i width nepotrebni. također, ovdje ima suvišnih tipografskih stilova...

2019-06-03 16:10 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +const DescriptionDescr = styled.div`
Kakvo je ovo ime komponente? Molio bih deskriptivnije ime. :) Ugl, dosta je slična komponenti Description. Iskoristi stilove koje možeš na  slj način const nekaKomponenta = styled(Description)``;

2019-06-03 16:10 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +const LocationDescr = styled.div`
ovo je isti pattern kao i za Description. Refaktorirati

2019-06-03 16:11 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +const Description = styled.div`
Nije mi jasno zašto se tipografski stilovi kao font-family, font-size, font-weight i sl. definirani na div komponenti. Za to treba koristiti <h1>---<h6> ili <p> element

2019-06-03 16:12 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +const Description = styled.div`
Nije mi jasno zašto se tipografski stilovi kao font-family, font-size, font-weight i sl. definirani na div komponenti. Za to treba koristiti
elemente tipa h1-h6 ili p.

2019-06-03 16:12 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +const ButtonDel = styled.div`
Opet button implementiran kao div....

2019-06-03 16:14 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +const ButtonEdit = styled.div`
Probaj napraviti jednu "root" komponentu npr. BaseButton koja će sadržavati stilove koje ponavljaš.. Ako trebaš raditi custom button sa dodatnim stilovima napravi to na način styled(BaseButton)

2019-06-03 16:15 UTC, ispoljari commented on src/UI/admin/components/available-hall/AdminAvailableHall.js
> +const AdminAvailableHallComponent = () => (
Ovo mora ići u poseban modul koji se zove AdminAvailableHall (isto kao i folder)... Styled components, sve iznad ove komp, moraju ići u file koji se zove AdminAvailableHallStyle. Ovaj pattern sam i ja koristio kada sam setupirao projekt, pa pogledaj kako je to izvedeno...

2019-06-03 16:16 UTC, ispoljari requested changes
molim revidirati prema mojim komentarima

2019-06-04 05:50 UTC, igorsustic commented
Zahvaljujem na review-u... Pozdrav!
Igor

On Mon, 3 Jun 2019, 18:16 Ivan Špoljarić, <notifications@github.com> wrote:

> *@ispoljari* requested changes on this pull request.
>
> molim revidirati prema mojim komentarima
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phys3/speck-academy-booking-app-client/pull/6?email_source=notifications&email_token=ALN2Z3OOCW5BYYLKUSOMY3LPYU7VDA5CNFSM4HSC3KH2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB2NCJ4Q#pullrequestreview-244983026>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALN2Z3MUAXKMNNUYPA4XYYTPYU7VDANCNFSM4HSC3KHQ>
> .
>

2019-06-11 16:30 UTC, merged