Admin requests page
phys3/speck-academy-booking-app-client pull request #9
Opened 2019-06-04 16:37 UTC by tomiiii55

2019-06-08 06:32 UTC, phys3 reviewed
odlicno, dobar breakdown komponente
treba koristiti styled.h1,.p,.button,.h2,....
nikako definirati height variabilnih divova

2019-06-08 06:32 UTC, phys3 commented on public/index.html
> +    <link
Bravo za trud ovo cemo iskoristiti svugdje 👍

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequest.js
> +      <EventDesc>
Inace puna i sto jasnija imena se koriste da neko ko cita odmah skuzi sta komponenta sluzi/radi

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequest.js
> +        <ButtonAcc>PRIHVATI</ButtonAcc>
isto puno bolje je ButtonAccept tih par slova znaci

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const ImageDiv = styled.div`
ako je image  onda koristis styled.img to ti dozvoljava da passas src attribute u komponentu bez deklariranja propsova. (po defaultu styled.img prima src i alt attribute) tak da to promjeniti

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const TextDiv = styled.div`
isto kao i gore ako je text onda stavis h2,h3,... ili p ili h1 ako je title stranice.
mozes u taj TextDiv staviti componentu text = styled.p (samo ponisti default margine) a text div da ti bude samo container. tako i drugdje nemoze svaki element biti div

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  font-weight: normal;
sve ovo di je normal je nepotrebno tako da mozes izbrisati

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  font-stretch: normal;
ko i gore

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  box-sizing: border-box;
ovaj border box ti se ponavlja cesto probaj viditi ako ga mozes stavit na parent pa da ga ostali inheritaju

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  font-stretch: normal;
remove normal

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  Podneseno,
inglish names for components

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const ButtonDen = styled.div`
ButtonDenied

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const ButtonDen = styled.div`
i styled.button

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const PhoneInput = styled.div`
nemas inputa u svojoj komponenti tak da neznam sta je ovo

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const Namesurname = styled.div`
NameSurname

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const TimeInput = styled.div`
nema inputa

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const TimeInput = styled.div`
probaj TimeDisplay

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  height: 64px;
nesmijes limitirati hight ni ovdje ni na cjeloj komponenti.
ako ima event dugacak opis sta ce ti se desit? brejkati ce se description i ono sve ispod njega i cjela komponenta
ti si na zeplinu gledao prvu komponentu al ako pogledas drugu ona ima 104px height.

2019-06-08 06:32 UTC, phys3 commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  height: 352px;
ovo ti brejka componentu prva u zeplinu je 352px druga je 392 treca je 296 nesmijes definirati height to sama komponenta odlucuje po contentu

2019-06-10 11:20 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequest.js
> +  Organizacija,
izbjegavati HR imena komponenti. primjeniti sve na ENG

2019-06-10 11:43 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequest.js
> +    <ButtonDiv>
malo bolje definirati imena ovih button komponenata. nešto je kontainer, nešto je AcceptButton a nešto DeleteButton

2019-06-10 11:44 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const ButtonDiv = styled.div`
Ovo nazvati ButtonsContainer

2019-06-10 11:44 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  height: 352px;
Height se ne zadaje explicitno

2019-06-10 11:45 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const ImageHall = styled.div`
Ovo nazvati ImageHall i koristiti img element a ne div... Ovaj cijeli modul je zaražen tzv. dividitisom :)

2019-06-10 11:46 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  font-weight: normal;
Obrisati nepotrebne stilove. Sve što ima value normal vjerojatno ne treba explicitno definirati jer je to defaultna vrijednost...

2019-06-10 11:47 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const EventName = styled.div`
Zašto je EventName div? Kada mu daš takvo ime očekujem da je to nekakav tipografski element npr. h ili p. Molim te ispravi ovo

2019-06-10 11:48 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const RightText = styled.div`
LeftText i Right Text su identične komponente. Kod se ponavlja. Ovo treba biti samo jedna komponenta sa smislenim imenom. Height se ne postavlja explicitno nego je funkcija sadržaja. Damjan je to već objasnio u svojim komentarima

2019-06-10 11:50 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +  box-sizing: border-box;
Nadovezao bih se na ovo. box-sizing: border box je postavljen kao globalni stil tako da ga nije potrebno ponovno definirati niti na jednoj komponenti....

2019-06-10 11:52 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const DatumInput = styled.div`
DatumInput i onda div element... Zašto? Ovo niti je input, niti treba biti div. Ime elementa mora biti usko povezano sa funkcijom/tipom tog elementa... Ako se radi o običnom tekstu, što ovdje i je slučaj, onda treba koristiti "najobičniji" <p> element.

2019-06-10 11:55 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const Time = styled.div`
Slične napomene kao i za DatumInput komponentu. Ovo nazovi TimeLabel. Umjesto div-a koristi `<p>` element itd. Ne definiraj nepotrebne stilove. Makni height property... Itd...

2019-06-10 11:56 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const TimeInput = styled.div`
Isti komentar kao i za DatumInput i Time komponentu

2019-06-10 11:56 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const ContactInfo = styled.div`
ovdje bi sad trebalo već biti jasno što sve treba promjeniti...

2019-06-10 11:56 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const NamesurnameInput = styled.div`
Refaktorirati prema već navedenim komentarima...

2019-06-10 11:57 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const Organizacija = styled.div`
Koristiti ENG imena komponenti

2019-06-10 11:57 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const OrganizacijaInput = styled.div`
Sve ove komponente pregledati i refaktorirati

2019-06-10 11:58 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const ButtonUp = styled.div`
Loše ime, div umjesto button-a, nepotreban box-sizing

2019-06-10 11:58 UTC, ispoljari commented on src/UI/admin/components/hall-request/AdminHallRequestStyle.js
> +const ButtonDown = styled.div`
Identična komponenta kao ButtonUp... Ponavljanje koda umjesto `const ButtonDown = styled(ButtonUp)`

2019-06-10 11:59 UTC, ispoljari requested changes
refaktorirati prema Damjanovim i Ivanovim komentarima

2019-06-12 19:56 UTC, merged